# Generated by Django 5.2.3 on 2025-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="isFollowing",
            field=models.BooleanField(default=True),
        ),
    ]
