# Generated by Django 5.2.3 on 2025-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_follow_isfollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="followers_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="follow",
            name="following_counter",
            field=models.IntegerField(default=0),
        ),
    ]
