# Generated by Django 5.2.3 on 2025-07-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_follow_followers_counter_follow_following_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="followers_counter",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following_counter",
        ),
    ]
