# Generated by Django 5.2.3 on 2025-07-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likes",
            name="isLiked",
        ),
    ]
